window.ASM_EVENTS = [
  /* ── 2025 upcoming ── */
  { title: 'Monthly Seminar — April',   start: '2025-04-17', color: '#0054a6', isUpcoming: true,
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Spring Symposium 2025',     start: '2025-05-16', color: '#003087', isUpcoming: true,
    icsFile: 'ics/spring-symposium-2025.ics',
    extendedProps: { location: 'Texas Medical Center, Houston, TX',
                     description: 'Frontiers in Infectious Disease',
                     type: 'symposium' } },
  { title: 'Monthly Seminar — May',     start: '2025-05-15', color: '#0054a6', isUpcoming: true,
    icsFile: 'ics/monthly-seminar-series.ics',
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Networking Mixer',          start: '2025-06-06', color: '#e8740c', isUpcoming: true,
    icsFile: 'ics/networking-mixer-2025.ics',
    extendedProps: { location: 'Houston, TX', description: 'Meet the Chapter — informal gathering',
                     type: 'networking' } },
  { title: 'Monthly Seminar — June',    start: '2025-06-19', color: '#0054a6', isUpcoming: true,
    icsFile: 'ics/monthly-seminar-series.ics',
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  /* ── Recurring Conferences — 2026 upcoming ── */
  { title: 'ASM Microbe 2026',          start: '2026-06-04', color: '#7c3aed', isUpcoming: true,
    url: 'https://asm.org/events/asm-microbe/home',
    icsFile: null,
    extendedProps: { location: 'Walter E. Washington Convention Center, Washington, D.C.',
                     description: 'ASM\'s flagship annual meeting covering all areas of microbiology and infectious disease. June 4–8, 2026.',
                     type: 'conference' } },
  { title: 'ASM BIG 2026',              start: '2026-10-11', color: '#7c3aed', isUpcoming: true,
    url: 'https://asm.org/events/asm-big/home',
    icsFile: null,
    extendedProps: { location: 'Hyatt Regency Washington on Capitol Hill, Washington, D.C.',
                     description: 'ASM Bioinformatics, Genomics and Big Data Conference. October 11–14, 2026.',
                     type: 'conference' } },
  /* ── Recurring Conferences — 2026 past ── */
  { title: 'TMC AMR 2026',              start: '2026-01-14', color: '#7c3aed',
    url: 'https://amr26.blogs.rice.edu/',
    icsFile: null,
    extendedProps: { location: 'BioScience Research Collaborative, Houston, TX',
                     description: '9th Annual Texas Medical Center Antimicrobial Resistance and Stewardship Conference. January 14–16, 2026.',
                     type: 'conference' } },
  { title: 'IMARI 2026',                start: '2026-01-28', color: '#7c3aed',
    url: 'https://imari.org/',
    icsFile: null,
    extendedProps: { location: 'SAHARA Las Vegas, Las Vegas, NV',
                     description: 'Inaugural Interdisciplinary Meeting on Antimicrobial Resistance and Innovation (ASM & IDSA). January 28–30, 2026.',
                     type: 'conference' } },
  { title: 'Texas ASM Spring 2026',     start: '2026-03-26', color: '#7c3aed',
    url: 'https://txasm.org/',
    icsFile: null,
    extendedProps: { location: 'Cedar Hill, TX',
                     description: 'Texas Branch ASM Spring 2026 meeting. March 26–28, 2026.',
                     type: 'conference' } },
  /* ── Recurring Conferences — 2025 past ── */
  { title: 'TMC AMR 2025',              start: '2025-01-15', color: '#7c3aed',
    url: 'https://amr25.blogs.rice.edu/',
    icsFile: null,
    extendedProps: { location: 'BioScience Research Collaborative, Houston, TX',
                     description: '8th Annual Texas Medical Center Antimicrobial Resistance and Stewardship Conference. January 15–17, 2025.',
                     type: 'conference' } },
  { title: 'ASM Microbe 2025',          start: '2025-06-19', color: '#7c3aed',
    url: 'https://asm.org/events/asm-microbe/home',
    icsFile: null,
    extendedProps: { location: 'Los Angeles Convention Center, Los Angeles, CA',
                     description: 'ASM\'s flagship annual meeting covering all areas of microbiology and infectious disease. June 19–23, 2025.',
                     type: 'conference' } },
  { title: 'Texas ASM Fall 2025',       start: '2025-10-30', color: '#7c3aed',
    url: 'https://txasm.org/',
    icsFile: null,
    extendedProps: { location: 'Tyler, TX',
                     description: 'Texas Branch ASM Fall 2025 meeting. October 30 – November 1, 2025.',
                     type: 'conference' } },
  { title: 'ASM Biofilms 2025',         start: '2025-11-09', color: '#7c3aed',
    url: 'https://asm.org/events/asm-biofilms/home',
    icsFile: null,
    extendedProps: { location: 'Portland Marriott Downtown Waterfront, Portland, OR',
                     description: 'ASM Conference on Biofilms. November 9–13, 2025. (Next ASM Biofilms conference: 2028)',
                     type: 'conference' } },
  /* ── Abstract Deadlines — 2026 upcoming ── */
  { title: 'Abstract Deadline — ASM BIG 2026 (Early)',  start: '2026-04-15', color: '#c084fc', isUpcoming: true,
    url: 'https://asm.org/events/asm-big/abstracts',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Early abstract deadline for ASM BIG 2026 (Bioinformatics, Genomics and Big Data Conference). 2:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  { title: 'Abstract Deadline — ASM BIG 2026',          start: '2026-06-17', color: '#c084fc', isUpcoming: true,
    url: 'https://asm.org/events/asm-big/abstracts',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'General abstract & travel award deadline for ASM BIG 2026. 2:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  /* ── Abstract Deadlines — 2026 past ── */
  { title: 'Abstract Deadline — ASM Microbe 2026',      start: '2026-01-21', color: '#c084fc',
    url: 'https://asm.org/events/asm-microbe/present/abstract-guidelines',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Regular abstract submission deadline for ASM Microbe 2026. 2:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  { title: 'Abstract Deadline — Texas ASM Spring 2026', start: '2026-02-27', color: '#c084fc',
    url: 'https://txasm.org/spring-2026-abstracts/',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Abstract submission deadline for Texas Branch ASM Spring 2026 meeting.',
                     type: 'abstract-deadline' } },
  /* ── Abstract Deadlines — 2025 past ── */
  { title: 'Abstract Deadline — ASM Microbe 2025',      start: '2025-01-22', color: '#c084fc',
    url: 'https://asm.org/events/asm-microbe/present',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Abstract submission deadline for ASM Microbe 2025. 12:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  { title: 'Abstract Deadline — ASM Biofilms 2025 (Early)', start: '2025-06-03', color: '#c084fc',
    url: 'https://asm.org/events/asm-biofilms/abstracts',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Early abstract deadline for ASM Conference on Biofilms 2025. 2:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  { title: 'Abstract Deadline — ASM Biofilms 2025',     start: '2025-08-06', color: '#c084fc',
    url: 'https://asm.org/events/asm-biofilms/abstracts',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'General abstract deadline for ASM Conference on Biofilms 2025. 2:00 p.m. ET.',
                     type: 'abstract-deadline' } },
  { title: 'Abstract Deadline — Texas ASM Fall 2025',   start: '2025-10-01', color: '#c084fc',
    url: 'https://txasm.org/',
    icsFile: null,
    extendedProps: { location: 'Online submission',
                     description: 'Abstract submission deadline for Texas Branch ASM Fall 2025 meeting.',
                     type: 'abstract-deadline' } },
  /* ── 2025 past ── */
  { title: 'Monthly Seminar — March',   start: '2025-03-20', color: '#0054a6',
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Networking Mixer — March',  start: '2025-03-07', color: '#e8740c',
    icsFile: null,
    extendedProps: { location: 'Houston, TX', description: 'Informal meet-and-greet',
                     type: 'networking' } },
  { title: 'Monthly Seminar — Feb',     start: '2025-02-20', color: '#0054a6',
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Research talk by TMC investigator',
                     type: 'seminar' } },
  { title: 'Grant Writing Workshop',    start: '2025-02-07', color: '#2e7d32',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center', description: 'NIH grant writing fundamentals',
                     type: 'workshop' } },
  /* ── 2024 ── */
  { title: 'Career Panel 2024',         start: '2024-11-15', color: '#2e7d32',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center', description: 'Industry vs. academia: perspectives from microbiologists',
                     type: 'workshop' } },
  { title: 'Fall Symposium 2024',       start: '2024-10-18', color: '#003087',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center, Houston, TX', description: 'Antimicrobial Resistance',
                     type: 'symposium' } },
  { title: 'Fall Kickoff Mixer 2024',   start: '2024-09-06', color: '#e8740c',
    icsFile: null,
    extendedProps: { location: 'Houston, TX', description: 'Chapter kickoff and new member welcome',
                     type: 'networking' } }
];
