window.ASM_EVENTS = [
  /* ── 2025 upcoming ── */
  { title: 'Monthly Seminar — April',   start: '2025-04-17', color: '#0054a6', isUpcoming: true,
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Spring Symposium 2025',     start: '2025-05-16', color: '#003087', isUpcoming: true,
    icsFile: 'ics/spring-symposium-2025.ics',
    extendedProps: { location: 'Texas Medical Center, Houston, TX',
                     description: 'Frontiers in Infectious Disease',
                     type: 'symposium' } },
  { title: 'Monthly Seminar — May',     start: '2025-05-15', color: '#0054a6', isUpcoming: true,
    icsFile: 'ics/monthly-seminar-series.ics',
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Networking Mixer',          start: '2025-06-06', color: '#e8740c', isUpcoming: true,
    icsFile: 'ics/networking-mixer-2025.ics',
    extendedProps: { location: 'Houston, TX', description: 'Meet the Chapter — informal gathering',
                     type: 'networking' } },
  { title: 'Monthly Seminar — June',    start: '2025-06-19', color: '#0054a6', isUpcoming: true,
    icsFile: 'ics/monthly-seminar-series.ics',
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  /* ── Recurring Conferences ── */
  { title: 'ASM Microbe 2025',          start: '2025-06-19', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'Los Angeles, CA',
                     description: 'ASM\'s flagship annual meeting covering all areas of microbiology and infectious disease. Visit asm.org for confirmed dates.',
                     type: 'conference' } },
  { title: 'ASM BIG 2025',              start: '2025-09-15', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'TBD',
                     description: 'ASM Bioinformatics, Genomics and Big Data Conference. Date approximate — visit asm.org for confirmed details.',
                     type: 'conference' } },
  { title: 'TMC AMR 2025',              start: '2025-09-22', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center, Houston, TX',
                     description: 'TMC Antimicrobial Resistance conference. Date approximate — check TMC for confirmed details.',
                     type: 'conference' } },
  { title: 'Texas ASM Meeting 2025',    start: '2025-10-10', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'Texas',
                     description: 'Texas Branch ASM annual meeting. Date approximate — visit asm.org/texas for confirmed details.',
                     type: 'conference' } },
  { title: 'ASM Biofilms 2025',         start: '2025-11-03', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'TBD',
                     description: 'ASM Biofilms Conference. Date approximate — visit asm.org for confirmed details.',
                     type: 'conference' } },
  { title: 'IMARI 2025',                start: '2025-11-17', color: '#7c3aed',
    icsFile: null,
    extendedProps: { location: 'TBD',
                     description: 'Interdisciplinary Meeting on Antimicrobial Resistance and Innovation. Date approximate — check organizers for confirmed details.',
                     type: 'conference' } },
  /* ── 2025 past ── */
  { title: 'Monthly Seminar — March',   start: '2025-03-20', color: '#0054a6',
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Speaker TBA',
                     type: 'seminar' } },
  { title: 'Networking Mixer — March',  start: '2025-03-07', color: '#e8740c',
    icsFile: null,
    extendedProps: { location: 'Houston, TX', description: 'Informal meet-and-greet',
                     type: 'networking' } },
  { title: 'Monthly Seminar — Feb',     start: '2025-02-20', color: '#0054a6',
    icsFile: null,
    extendedProps: { location: 'Rotating TMC venue', description: 'Research talk by TMC investigator',
                     type: 'seminar' } },
  { title: 'Grant Writing Workshop',    start: '2025-02-07', color: '#2e7d32',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center', description: 'NIH grant writing fundamentals',
                     type: 'workshop' } },
  /* ── 2024 ── */
  { title: 'Career Panel 2024',         start: '2024-11-15', color: '#2e7d32',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center', description: 'Industry vs. academia: perspectives from microbiologists',
                     type: 'workshop' } },
  { title: 'Fall Symposium 2024',       start: '2024-10-18', color: '#003087',
    icsFile: null,
    extendedProps: { location: 'Texas Medical Center, Houston, TX', description: 'Antimicrobial Resistance',
                     type: 'symposium' } },
  { title: 'Fall Kickoff Mixer 2024',   start: '2024-09-06', color: '#e8740c',
    icsFile: null,
    extendedProps: { location: 'Houston, TX', description: 'Chapter kickoff and new member welcome',
                     type: 'networking' } }
];
